.PHONY: run build-linux build-android build-windows analyze clean

run:
	flutter run

build-linux:
	flutter build linux

build-android:
	flutter build apk

build-windows:
	flutter build windows

analyze:
	flutter analyze

clean:
	flutter clean