name: ocp_app
description: OCP Flutter application — presentation layer and workspaces.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  mock_device:
    path: ../../tools/mock_device
  mock_position_feed:
    path: ../../tools/mock_position_feed
  ocp_bridge_meshtastic:
    path: ../../packages/ocp_bridge_meshtastic
  ocp_core:
    path: ../../packages/ocp_core
  ocp_maps:
    path: ../../packages/ocp_maps
  ocp_odp:
    path: ../../packages/ocp_odp
  ocp_onp:
    path: ../../packages/ocp_onp
  ocp_plugin_api:
    path: ../../packages/ocp_plugin_api
  ocp_plugin_example:
    path: ../../packages/ocp_plugin_example
  ocp_storage:
    path: ../../packages/ocp_storage
  ocp_transport:
    path: ../../packages/ocp_transport
  ocp_transport_ble:
    path: ../../packages/ocp_transport_ble
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
