name: mock_device
description: ODP simulator device for loopback testing.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  ocp_odp:
    path: ../../packages/ocp_odp

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^5.0.0
